### ISSUE TITLE
JWT Secret is Hardcoded

### ISSUE THREAD

**Issue by Helithumper** [HackUCF/OnboardLite#5]
This was originally found from SemGrep:

```
    index.py
       python.jwt.security.jwt-hardcode.jwt-python-hardcoded-secret
          Hardcoded JWT secret or private key is used. This is a Insufficiently Protected Credentials
          weakness: https://cwe.mitre.org/data/definitions/522.html Consider using an appropriate
          security mechanism to protect the credentials (e.g. keeping secrets in environment
          variables)
          Details: https://sg.run/l2E9

          196┆ options.get("jwt").get("secret"),
            ⋮┆----------------------------------------
          196┆ options.get("jwt").get("secret"),
```

Instead, the JWT secret should be generated each time the app is started (unless there are clustering plans but I don't think that's necessary to plan for atm.

Maybe just generate some long random string using https://docs.python.org/3/library/secrets.html each time the app starts. All sessions are terminated with the application but IMHO this is an easy idea to never have to deal with session secret compromise aside from variable theft during runtime.

**Comment by jeffreydivi** [comment]
To generalize to the entirety of `options`, plaintext secrets is currently an accepted risk due to the sheer number of secrets and no cloud-y mechanism for gating them. I'll roundtable this and see if fixing can be added to the timeline.

In my opinion, encryption is the best strategy and could be handled transparently by the `Options` helper class (see: #8), and the spawning systemd config would need to have the decryption key as an environment variable. However, that file cannot be readable by the current user at all.
